/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./items/shirt/s2.gltf 
*/

import { useGLTF, useTexture } from '@react-three/drei';
import React from 'react';
import { Mesh, MeshStandardMaterial, RepeatWrapping } from 'three';

export function Model(properties) {
    const { nodes, materials } = useGLTF('/items/shirt/s2.gltf');

    const [texture] = useTexture(['/items/shirt/s2.png']);

    texture.wrapS = RepeatWrapping;
    texture.wrapT = RepeatWrapping;
    texture.repeat.set(1, 1);
    console.log(texture);

    const myMaterial = new MeshStandardMaterial({ map: texture });

    return (
        <group {...properties} dispose={undefined}>
            <group position={[0, -1.3, 0]}>
                <mesh
                    geometry={nodes.mesh_0.geometry}
                    material={nodes.mesh_0.material}
                />
                <mesh
                    geometry={nodes.mesh_0_1.geometry}
                    material={nodes.mesh_0_1.material}
                />
                <mesh
                    geometry={nodes.mesh_0_2.geometry}
                    material={nodes.mesh_0_2.material}
                />
                <mesh
                    geometry={nodes.mesh_1.geometry}
                    material={nodes.mesh_1.material}
                />
                <mesh
                    geometry={nodes.mesh_1_1.geometry}
                    material={nodes.mesh_1_1.material}
                />
                <mesh
                    geometry={nodes.mesh_1_2.geometry}
                    material={nodes.mesh_1_2.material}
                />
                <primitive
                    object={new Mesh(nodes.mesh_2.geometry, myMaterial)}
                />
                {/* <mesh>
                    <bufferGeometry geometry={nodes.mesh_2.geometry} />
                    <meshStandardMaterial {...myMaterial} />
                </mesh> */}
                <mesh
                    geometry={nodes.mesh_2_1.geometry}
                    material={nodes.mesh_2_1.material}
                />
                <mesh
                    geometry={nodes.mesh_2_2.geometry}
                    material={nodes.mesh_2_2.material}
                />
                <mesh
                    geometry={nodes.mesh_3.geometry}
                    material={nodes.mesh_3.material}
                />
                <mesh
                    geometry={nodes.mesh_3_1.geometry}
                    material={nodes.mesh_3_1.material}
                />
                <mesh
                    geometry={nodes.mesh_3_2.geometry}
                    material={nodes.mesh_3_2.material}
                />
                <mesh
                    geometry={nodes.mesh_4.geometry}
                    material={nodes.mesh_4.material}
                />
                <mesh
                    geometry={nodes.mesh_4_1.geometry}
                    material={nodes.mesh_4_1.material}
                />
                <mesh
                    geometry={nodes.mesh_4_2.geometry}
                    material={nodes.mesh_4_2.material}
                />
                <mesh
                    geometry={nodes.mesh_5.geometry}
                    material={nodes.mesh_5.material}
                />
                <mesh
                    geometry={nodes.mesh_5_1.geometry}
                    material={nodes.mesh_5_1.material}
                />
                <mesh
                    geometry={nodes.mesh_5_2.geometry}
                    material={nodes.mesh_5_2.material}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/items/shirt/s2.gltf');
useTexture.preload('/items/shirt/s2.png');
